### ISSUE TITLE
Toggle mute/unmute switch while playing audio

### ISSUE THREAD

**Issue by aliat110** [Rishav-01/Musify-App#1]
- Add a functionality to toggle Mute/Unmute

**Comment by aliat110** [comment]
@Rishav-01 Please have a look

**Comment by Rishav-01** [comment]
Hey Bro !

Thanks for contributing towards my Repo but I am still facing the issue

You can check out the Latest issue that I have posted

**Comment by pawas108ram** [comment]
Hello can i resolve this issue

**Comment by Rishav-01** [comment]
Yeah ! You can solve this issue
