### ISSUE TITLE
Muting / Unmuting Functionality while playing audio

### ISSUE THREAD

**Issue by Rishav-01** [Rishav-01/Musify-App#3]
Hey !

I am happy that you are willing to Contribute towards my Website !!

So, I want to add a feature to this website that whenever any music is playing and I click on the button on songs list, then the music should be paused along with, the glow effect should go off, master play button is toggled, the timer is paused and the gif which is active should be hidden..
I have also provided an image for your reference for better understanding in the  [Issue](https://github.com/Rishav-01/Musify-App/tree/main/Issue) Folder

I am frustrated doing this alone and therefore I want your Contribution !!

**Comment by senpa1-13** [comment]
Hi can you add some picture or gif to explain the issue

**Comment by Rishav-01** [comment]
Yeah !
You can see the image in [Issue](https://github.com/Rishav-01/Musify-App/tree/main/Issue) folder in My Repo. I have explained well there

**Comment by Rishav-01** [comment]
Hey Buddy !

Any updates regarding the issue ?
@senpa1-13

**Comment by senpa1-13** [comment]
> Hey Buddy !
> 
> Any updates regarding the issue ?
> @senpa1-13 

Hey, I was working on another issue. But I'll start working on it tomorrow. Can you elaborate on the issue with the help of a gif or something as it is difficult to comprehend the issue with text.

**Comment by Rishav-01** [comment]
Hey !
I have added a video capture for your reference, it will be clear to you what is the issue.
Link -: [Issue](https://github.com/Rishav-01/Musify-App/tree/main/Issue)
@senpa1-13
